#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename

#SBATCH --time=24:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=16   # 16 processor core(s) per node
#SBATCH --partition=scavenger  # huge node(s)
#SBATCH --job-name="maize_SNPS_incresing_order"
#SBATCH --mail-user=panchali@iastate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output="Increasing_sorting.output" # job standard output file (%j replaced by job id)
#SBATCH --error="Increasing_sorting.error" # job standard error file (%j replaced by job id)

awk -F"\t" 'NR == 1 || $2 == "1"' modified_joined_teosinte _data.txt | sort -k3,3n | awk -F"\t" -v OFS="\t" 'NR == 1 || $3 != "0" {print $0; next} { $3 = "?"; print }' > teosinte_chr_1_inc.txt
awk -F"\t" 'NR == 1 || $2 == "2"' modified_joined_teosinte_data.txt | sort -k3,3n | awk -F"\t" -v OFS="\t" 'NR == 1 || $3 != "0" {print $0; next} { $3 = "?"; print }' > teosinte_chr_2_inc.txt
awk -F"\t" 'NR == 1 || $2 == "3"' modified_joined_teosinte_data.txt | sort -k3,3n | awk -F"\t" -v OFS="\t" 'NR == 1 || $3 != "0" {print $0; next} { $3 = "?"; print }' > teosinte_chr_3_inc.txt
awk -F"\t" 'NR == 1 || $2 == "4"' modified_joined_teosinte_data.txt | sort -k3,3n | awk -F"\t" -v OFS="\t" 'NR == 1 || $3 != "0" {print $0; next} { $3 = "?"; print }' > teosinte_chr_4_inc.txt
awk -F"\t" 'NR == 1 || $2 == "5"' modified_joined_teosinte_data.txt | sort -k3,3n | awk -F"\t" -v OFS="\t" 'NR == 1 || $3 != "0" {print $0; next} { $3 = "?"; print }' > teosinte_chr_5_inc.txt
awk -F"\t" 'NR == 1 || $2 == "6"' modified_joined_teosinte_data.txt | sort -k3,3n | awk -F"\t" -v OFS="\t" 'NR == 1 || $3 != "0" {print $0; next} { $3 = "?"; print }' > teosinte_chr_6_inc.txt
awk -F"\t" 'NR == 1 || $2 == "7"' modified_joined_teosinte_data.txt | sort -k3,3n | awk -F"\t" -v OFS="\t" 'NR == 1 || $3 != "0" {print $0; next} { $3 = "?"; print }' > teosinte_chr_7_inc.txt
awk -F"\t" 'NR == 1 || $2 == "8"' modified_joined_teosinte _data.txt | sort -k3,3n | awk -F"\t" -v OFS="\t" 'NR == 1 || $3 != "0" {print $0; next} { $3 = "?"; print }' > teosinte_chr_8_inc.txt
awk -F"\t" 'NR == 1 || $2 == "9"' modified_joined_teosinte_data.txt | sort -k3,3n | awk -F"\t" -v OFS="\t" 'NR == 1 || $3 != "0" {print $0; next} { $3 = "?"; print }' > teosinte_chr_9_inc.txt
awk -F"\t" 'NR == 1 || $2 == "10"' modified_joined_teosinte_data.txt | sort -k3,3n | awk -F"\t" -v OFS="\t" 'NR == 1 || $3 != "0" {print $0; next} { $3 = "?"; print }' > teosinte_chr_10_inc.txt

